name: rfid77workflow

version: 1.1.2
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cherry_toast: ^1.6.4
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^3.0.0
  segmented_button_slide: ^1.0.4
  stop_watch_timer: ^3.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  lint: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/brand/
    - assets/lottie/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/brand/icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
